env:
  node: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

settings:
  import/resolver: webpack
  react:
    version: '16.6.0'

rules:
  import/prefer-default-export: 0
  import/no-unresolved: 0
  operator-linebreak: 0
  react/display-name: 0
  react/prop-types: 0
  no-console: 1
