root: true

env:
  node: true
  browser: true

parser: '@typescript-eslint/parser'

extends:
  - 'airbnb-base'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'

ignorePatterns:
  - '/dist'

plugins:
  - '@typescript-eslint'
  - 'import'

settings:
  'import/resolver':
    node:
      extensions: ['.js', '.ts', '.tsx']
  react:
    version: '17.0.2'

rules:
  function-paren-newline: 0
  no-confusing-arrow: 0
  implicit-arrow-linebreak: 0
  object-curly-newline: 0
  operator-linebreak: 0
  import/prefer-default-export: 0
  no-console: 1
  arrow-parens:
    - error
    - as-needed
  comma-dangle:
    - error
    - objects: only-multiline
      arrays: only-multiline
      functions: ignore
      imports: only-multiline
  no-param-reassign:
    - error
    - props: false
  no-return-assign:
    - error
    - except-parens
  react/prop-types: 0
  react/display-name: 1
  import/extensions: off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': ['error']
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-empty-interface': off
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars': ['error']
