install:
	npm i

start:
	npx webpack-dev-server

build:
	npx webpack

lint:
	npx eslint --quiet .

lint-fix:
	npx eslint --fix --quiet .

lint-with-warn:
	npx eslint .

test:
	npx jest --watch

test-one-file:
	npx jest --watch $(arg)
