install:
	npm i

start:
	npm start

build:
	npm run build

start-production:
	npm run start:prod

lint:
	npx eslint --quiet .

lint-fix:
	npx eslint --fix --quiet .

lint-with-warn:
	npx eslint .

.PHONY: build
